package com.came.stock.web.layer;

import java.io.Serializable;

import org.zkoss.zk.ui.Component;
import org.zkoss.zk.ui.select.SelectorComposer;

public class LayerWebTag extends SelectorComposer<Component> implements Serializable{

	private static final long serialVersionUID = 5386595702665056228L;
	
	protected String TAG_LOGINVM_ESCRIBENOS;
	protected String TAG_LOGINVM_USUARIO;
	protected String TAG_LOGINVM_CONTRA;
	protected String TAG_LOGINVM_ACCE;
	protected String TAG_LOGINVM_AUTENT;
	protected String TAG_LOGINVM_PROVEEDORES;
	
	
	protected String TAG_MENUVM_SUBTITLE1_REQ;
	protected String TAG_MENUVM_SUBTITLE1_ITEM_REQ;
	protected String TAG_MENUVM_SUBTITLE1_ITEM_CONCENTR;
	protected String TAG_MENUVM_SUBTITLE2_COTIZACIONES;
	protected String TAG_MENUVM_SUBTITLE2_ITEM_COT; 
	protected String TAG_MENUVM_SUBTITLE3_ORDENCOMPRA;
	protected String TAG_MENUVM_SUBTITLE3_ITEM_ORDENCOMPRA;
	protected String TAG_MENUVM_SUBTITLE3_ITEM_CONTROL;
	protected String TAG_MENUVM_SUBTITLE3_ITEM_KARDEX;
	protected String TAG_MENUVM_SUBTITLE4_PANELCONTROL;
	protected String TAG_MENUVM_SUBTITLE4_ITEM_CATA;
	protected String TAG_MENUVM_SUBTITLE4_ITEM_PRODUC;
	protected String TAG_MENUVM_SUBTITLE4_ITEM_PROVEEDOR;
	protected String TAG_MENUVM_SUBTITLE4_ITEM_CLIENTES;
	protected String TAG_MENUVM_SUBTITLE4_ITEM_USUARIO;
	protected String TAG_MENUVM_SUBTITLE5_PERFIL;
	protected String TAG_MENUVM_SUBTITLE5_ITEM_PERFIL;
	
	protected String TAG_HEADERVM_TOOLTIP_CERRAR;
	protected String TAG_HEADERVM_CODE_MESSAGE;
	protected String TAG_HEADERVM_CODE_TITLE;


	
	protected String GENERICZUL_TIP_CANTIDAD_PRODUCTO;
	protected String GENERICZUL_TIP_CLAVE_AREA;
	protected String GENERICZUL_TIP_FOLIO_REQUISICION;
	protected String GENERICZUL_LABEL_BUSCADOR;
	protected String GENERICZUL_TIP_GUARDAR_CAMBIOS;
	protected String GENERICZUL_TIP_REQUISICIONPDF;
	protected String REQUISICIONZUL_TIP_SALVAR_CAMBIOS;
	protected String GENERICZUL_TIP_BUSCADOR;
	protected String GENERICZUL_TIP_CLAVE_PRODUCTO;
	protected String GENERICZUL_COMMAND_CANCELAR;
	protected String GENERICZUL_COMMAND_ACEPTAR;
	protected String GENERICZUL_LABEL_ACTIVO;
	protected String GENERICZUL_LABEL_ACTUALIZADO;
	protected String GENERICZUL_LABEL_APATERNO_ABR;
	protected String GENERICZUL_LABEL_APATERNO;
	protected String GENERICZUL_LABEL_AMATERNO_ABR;
	protected String GENERICZUL_LABEL_AMATERNO;
	protected String GENERICZUL_LABEL_AREA_UR;
	protected String GENERICZUL_LABEL_ATENCION;
	protected String GENERICZUL_LABEL_BANCO;
	protected String GENERICZUL_LABEL_CALLE;
	protected String GENERICZUL_LABEL_CIUDAD;
	protected String GENERICZUL_LABEL_CLAVE;
	protected String GENERICZUL_LABEL_CLABE;
	protected String GENERICZUL_LABEL_CLAVE_ARMOMIZADA;
	protected String GENERICZUL_LABEL_CONTRASENA;
	protected String GENERICZUL_LABEL_CONTRASENA_REPETIR;
	protected String GENERICZUL_LABEL_CUENTA_BANCARIA;
	protected String GENERICZUL_LABEL_CURP;// = CURP:
	protected String GENERICZUL_LABEL_CODIGO_BARRAS_ABR;
	protected String GENERICZUL_LABEL_CODIGO_POSTAL;
	protected String GENERICZUL_LABEL_CODIGO_POSTAL_ABR;
	protected String GENERICZUL_LABEL_COLONIA;
	protected String GENERICZUL_LABEL_COSTO_UNITARIO;
	protected String GENERICZUL_LABEL_DESCRIPCION;
	protected String GENERICZUL_LABEL_DIRECCION;
	protected String GENERICZUL_LABEL_EMAIL;
	protected String GENERICZUL_LABEL_EN_EXISTENCIA;
	protected String GENERICZUL_LABEL_ESTADO;
	protected String GENERICZUL_LABEL_ENTIDAD;
	protected String GENERICZUL_LABEL_EXTENSION;
	protected String GENERICZUL_LABEL_FAMILIA;
	protected String GENERICZUL_LABEL_FAX;
	protected String GENERICZUL_LABEL_FECHA;
	protected String GENERICZUL_LABEL_FECHA_CADUCIDAD;
	protected String GENERICZUL_LABEL_FOLIO;
	protected String GENERICZUL_LABEL_GIRO;
	protected String GENERICZUL_LABEL_IMAGEN;
	protected String GENERICZUL_LABEL_MARCA;
	protected String GENERICZUL_LABEL_MAXIMO;
	protected String GENERICZUL_LABEL_MINIMO;
	protected String GENERICZUL_LABEL_MODELO;
	protected String GENERICZUL_LABEL_MONEDA;
	protected String GENERICZUL_LABEL_MOVIL;
	protected String GENERICZUL_LABEL_MUNICIPIO;
	protected String GENERICZUL_LABEL_NATURALEZA;
	protected String GENERICZUL_LABEL_NOMBRE;
	protected String GENERICZUL_LABEL_NUMERO;
	protected String GENERICZUL_LABEL_NUMERO_EXTERIOR;
	protected String GENERICZUL_LABEL_NUMERO_EXTERIOR_ABR;
	protected String GENERICZUL_LABEL_NUMERO_INTERIOR;
	protected String GENERICZUL_LABEL_NUMERO_INTERIOR_ABR;
	protected String GENERICZUL_LABEL_PAGINA_WEB;
	protected String GENERICZUL_LABEL_PAIS;
	protected String GENERICZUL_LABEL_PARTIDA_GENERICA;
	protected String GENERICZUL_LABEL_PROVEEDOR;
	protected String GENERICZUL_LABEL_RAZON_SOCIAL;
	protected String GENERICZUL_LABEL_REPOSICION;
	protected String GENERICZUL_LABEL_RFC;
	protected String GENERICZUL_LABEL_TELEFONO;
	protected String GENERICZUL_LABEL_UNIDAD;
	protected String GENERICZUL_LABEL_USUARIO;
	protected String GENERICZUL_COLUMN_ABREVIATURA;
	protected String GENERICZUL_COLUMN_ACTIVAR;
	protected String GENERICZUL_COLUMN_ACTUALIZACION;
	protected String GENERICZUL_COLUMN_AREA;
	protected String GENERICZUL_COLUMN_ARTICULO;
	protected String GENERICZUL_COLUMN_CLAVE;
	protected String GENERICZUL_COLUMN_CLAVE_ABR;
	protected String GENERICZUL_COLUMN_CVL_PR;
	protected String GENERICZUL_COLUMN_CALLE;
	protected String GENERICZUL_COLUMN_CANTIDAD_ABR;
	protected String GENERICZUL_COLUMN_CANTIDAD;
	protected String GENERICZUL_COLUMN_CP;
	protected String GENERICZUL_COLUMN_COLONI_ABR;
	protected String GENERICZUL_COLUMN_COTIZACION;
	protected String GENERICZUL_COLUMN_DESCRIPCION;
	protected String GENERICZUL_COLUMN_ESTADO_ABR;
	protected String GENERICZUL_COLUMN_EMAIL;
	protected String GENERICZUL_COLUMN_EN_EXISTENCIA;
	protected String GENERICZUL_COLUMN_FOLIO_REQ;
	protected String GENERICZUL_COLUMN_FOLIO;
	protected String GENERICZUL_COLUMN_FECHA;
	protected String GENERICZUL_COLUMN_IMPORTE;
	protected String GENERICZUL_COLUMN_MARCA;
	protected String GENERICZUL_COLUMN_MUNICIPIO_ABR;
	protected String GENERICZUL_COLUMN_MUNICIPIO;
	protected String GENERICZUL_COLUMN_NATURALEZA;
	protected String GENERICZUL_COLUMN_NO;
	protected String GENERICZUL_COLUMN_NUMERO_ABR;
	protected String GENERICZUL_COLUMN_NUMERO;
	protected String GENERICZUL_COLUMN_NOMBRE;
	protected String GENERICZUL_COLUMN_NOMBRE_COMPLETO;
	protected String GENERICZUL_COLUMN_ORDEN_COMPRA;
	protected String GENERICZUL_COLUMN_ORGANIZACION;
	protected String GENERICZUL_COLUMN_PROVEEDOR;
	protected String GENERICZUL_COLUMN_PRECIO;
	protected String GENERICZUL_COLUMN_PRECIO_UNITARIO;
	protected String GENERICZUL_COLUMN_PRIVILEGIOS;
	protected String GENERICZUL_COLUMN_PRODUCTO;
	protected String GENERICZUL_COLUMN_PARTIDA_GENERICA;
	protected String GENERICZUL_COLUMN_REGISTRO;
	protected String GENERICZUL_COLUMN_SIMBOLO;
	protected String GENERICZUL_COLUMN_STOCK;
	protected String GENERICZUL_COLUMN_TOTAL;
	protected String GENERICZUL_COLUMN_UNIDAD_MEDIDA;
	protected String GENERICZUL_COLUMN_UNIDAD;
	protected String GENERICZUL_COLUMN_UR;
	protected String GENERICZUL_COLUMN_USUARIO;
	protected String GENERICZUL_COLUMN_VIGENCIA_INICIO;
	protected String GENERICZUL_COLUMN_VIGENCIA_FIN;
	
	protected String GENERICMESSAGE_NO_EXISTE_USUARIO;
	protected String GENERICMESSAGE_INGRESAR_VALOR_REGISTRO;
	protected String GENERICMESSAGE_SERVICIO_NO_ACTIVADO;
	protected String GENERICMESSAGE_CREDENCIALES_INCORRECTAS;

	
	protected String REQUISICIONZUL_TITLE;// = REQUISICIONES | REQUISICIÓN:
	protected String REQUISICIONZUL_TIP_REQUISICION_NUEVA;// = REQUISICIONES NUEVAS
	protected String REQUISICIONZUL_TIP_REQUISICION_CANCELADA;// = REQUISICIONES CANCELADAS
	protected String REQUISICIONZUL_TIP_REQUISICION_ACEPTADA;// = REQUISICIONES ACEPTADAS
	protected String REQUISICIONZUL_TIP_BUSCA_REQUISICION;// = BUSCAR REQUISICIÓN
	protected String REQUISICIONZUL_TITLE_LISTAPRODUCTOS;// = LISTA DE PRODUCTOS
	protected String REQUISICIONZUL_TITLE_BANDEJA_REQUISICION;// = BANDEJA DE REQUISICIONES
	protected String REQUISICIONZUL_LABEL_AREASOLICITANTE;// = ÁREA SOLICITANTE (UR):
	protected String REQUISICIONZUL_LABEL_PROGRAMA;// = PROGRAMA:
	protected String REQUISICIONZUL_LABEL_PROYECTO;// = PROYECTO:
	protected String REQUISICIONZUL_LABEL_FUENTE_FINANCIAMIENTO;// = FUENTE DE FINANCIAMIENTO
	protected String REQUISICIONZUL_LABEL_PUESTO;// = PUESTO:
	protected String REQUISICIONZUL_LABEL_JUSTIFICACION;// = JUSTIFICACIÓN:
	protected String REQUISICIONZUL_LABEL_NUMERO_INVENTARIO;// = NÚMERO DE INVENTARIO:
	protected String REQUISICIONZUL_LABEL_PRODUCTOS_COUNT;// = PRODUCTOS:
	protected String REQUISICIONZUL_LABEL_CONTRATO;// = CONTRATO:
	protected String REQUISICIONZUL_LABEL_ALMACEN;// = ALMACÉN:
	protected String REQUISICIONZUL_LABEL_CONSUMO;// = CONSUMO:
	protected String REQUISICIONZUL_TIP_COMMAND_REQUISICIONNUEVA;// = NUEVA REQUISICIÓN
	protected String REQUISICIONZUL_TIP_BUSCAR_AREA;// = BUSCAR ÁREA (UR)
	protected String REQUISICIONZUL_TIP_BUSCAR_PROGRAMA;// = BUSCAR PROGRAMA
	protected String REQUISICIONZUL_TIP_BUSCAR_PROYECTO;// = BUSCAR PROYECTO
	protected String REQUISICIONZUL_TIP_BUSCAR_FUENTE_FINANCIAMIENTO;// = BUSCAR FUENTE DE FINANCIAMIENTO
	protected String REQUISICIONZUL_TIP_BUSCAR_JUSTIFICACION;// = BUSCAR JUSTIFICACIÓN
	protected String REQUISICIONZUL_TIP_BUSCAR_PRODUCTOS;// = ASISTENTE PARA BÚSQUEDA DE PRODUCTOS
	protected String REQUISICIONZUL_TIP_BUSCAR_PARTIDA_GENERICA;// = BUSCAR PARTIDA GENÉRICA
	protected String REQUISICIONZUL_TIP_PRODUCTOS_ENTREGADOS;// = PRODUCTOS ENTREGADOS
	protected String REQUISICIONZUL_TIP_ADD_PRODUCTO;// = AGREGAR PRODUCTO A LA LISTA
	protected String REQUISICIONZUL_TIP_REMOVE_PRODUCTO;// = QUITAR PRODUCTO DE LA LISTA
	protected String REQUISICIONZUL_BUSQUEDA_VACIA;
	protected String REQUISICIONZUL_BANDEJA_VACIA;
	
	protected String WINDOW_SELECT_UR_TITLE;
	protected String WINDOW_SELECT_UR_EMPTY;
	protected String WINDOW_SELECT_PROYECTO_TITLE;
	protected String WINDOW_SELECT_PROYECTO_EMPTY;
	
	protected String WINDOW_SELECT_PROGRAMA_TITLE;
	protected String WINDOW_SELECT_PROGRAMA_EMPTY;
	protected String WINDOW_SELECT_PARTIDA_GENERICA_TITLE;
	protected String WINDOW_SELECT_PARTIDA_GENERICA_EMPTY;
	protected String WINDOW_SELECT_JUSTIFICACION_TITLE;
	protected String WINDOW_SELECT_JUSTIFICACION_EMPTY;
	protected String WINDOW_SELECT_FUENTE_FINANCIAMIENTO_TITLE;
	protected String WINDOW_SELECT_FUENTE_FINANCIAMIENTO_EMPTY;
	protected String WINDOW_BUSCADOR_PRODUCTOS_TITLE;
	protected String WINDOW_BUSCADOR_PRODUCTOS_EMPTY;

	protected String WINDOW_MESSAGE1_TITLE;
	protected String WINDOW_MESSAGE1_CONTENT;
	protected String WINDOW_MESSAGE2_CONTENT;
	
	protected String REQUISICIONVM_MESSAGE1_CONTENT;
	protected String REQUISICIONVM_MESSAGE2_CONTENT1;
	protected String REQUISICIONVM_MESSAGE2_CONTENT2;
	protected String REQUISICIONVM_MESSAGE3_CONTENT1;
	protected String REQUISICIONVM_MESSAGE3_CONTENT2;
	protected String REQUISICIONVM_MESSAGE3_CONTENT3;
	protected String REQUISICIONVM_MESSAGE_EMAIL_SUBJECT_NUEVA_REQ;
	protected String REQUISICIONVM_MESSAGE_EMAIL_MESSAGE_NUEVA_REQ; 
	protected String REQUISICIONVM_MESSAGE_EMAIL_FAIL_REQ;
	protected String REQUISICIONVM_MESSAGE1_VALIDA_PRODUCTO;
	protected String REQUISICIONVM_MESSAGE2_VALIDA_PRODUCTO;
	protected String REQUISICIONVM_MESSAGE3_VALIDA_PRODUCTO;
	protected String REQUISICIONVM_MESSAGE4_VALIDA_PRODUCTO;
	protected String REQUISICIONVM_MESSAGE5_VALIDA_PRODUCTO;
	protected String REQUISICIONVM_MESSAGE6_VALIDA_PRODUCTO;
	protected String REQUISICIONVM_MESSAGE7_VALIDA_PRODUCTO;
	protected String REQUISICIONVM_MESSAGE8_VALIDA_PRODUCTO;
	protected String REQUISICIONVM_MESSAGE9_VALIDA_PRODUCTO;
	protected String REQUISICIONVM_MESSAGE10_CONTENT1;
	protected String REQUISICIONVM_MESSAGE11_CONTENT1;
	protected String REQUISICIONVM_MESSAGE11_CONTENT2;
	protected String REQUISICIONVM_MESSAGE12_CONTENT1;
	protected String REQUISICIONVM_MESSAGE12_CONTENT2;
	protected String REQUISICIONVM_MESSAGE13_PRODUCTO_DUPLICADO;
	protected String REQUISICIONVM_MESSAGE14_RESULTADO_VACIO_PDF;
	protected String REQUISICIONVM_MESSAGE15_CONTENT1_ALMACEN_AREA;
	protected String REQUISICIONVM_MESSAGE15_CONTENT2_ALMACEN_AREA;
	protected String REQUISICIONZUL_TIP_REQUISICION_PENDIENTE;
	protected String REQUISICIONZUL_LIST1;
	
	protected String CONCENTRADOZUL_TIP_GENERAR_COTIZACION;
	protected String CONCENTRADOZUL_TITLE_MAIN_PANEL;
	
	protected String CONCENTRADOVM_MESSAGE1_CONTENT;
	protected String CONCENTRADOVM_MESSAGE2_CONTENT;
	protected String CONCENTRADOVM_MESSAGE3_TITLE;
	protected String CONCENTRADOVM_MESSAGE3_CONTENT1;
	protected String CONCENTRADOVM_MESSAGE4_BUSCAR_PRODUCTO_TITLE;
	protected String CONCENTRADOVM_MESSAGE4_BUSCAR_PRODUCTO_CONTENT1;
	protected String CONCENTRADOVM_MESSAGE4_BUSCAR_PRODUCTO_CONTENT2;
	protected String CONCENTRADOVM_MESSAGE4_BUSCAR_PRODUCTO_CONTENT3;
	protected String CONCENTRADOVM_MESSAGE5_REMOVE_CONTENT1;
	protected String CONCENTRADOVM_MESSAGE5_REMOVE_CONTENT2;
	protected String CONCENTRADOVM_MESSAGE6_CANCELAR_CONTENT;
	protected String CONCENTRADOVM_MESSAGE6_CANCELAR_CONTENT2;
	protected String CONCENTRADOVM_MESSAGE7_SAVE_COTIZACION_CONTENT1;
	protected String CONCENTRADOVM_MESSAGE7_SAVE_COTIZACION_CONTENT2;
	protected String CONCENTRADOVM_MESSAGE8_UPDATE;
	
	protected String GLOBAL_INFO_MESSAGE1;
	protected String GLOBAL_INFO_STATUS_NUEVO;
	protected String GLOBAL_INFO_STATUS_CANCELADA;
	protected String GLOBAL_INFO_STATUS_ACEPTADO;
	protected String GLOBAL_INFO_PDF_GENERADO;
	protected String GLOBAL_INFO_PDF_CONFIRMATION;

	
	public String getTAG_LOGINVM_ESCRIBENOS() {
		return TAG_LOGINVM_ESCRIBENOS;
	}
	public String getTAG_LOGINVM_USUARIO() {
		return TAG_LOGINVM_USUARIO;
	}
	public String getTAG_LOGINVM_CONTRA() {
		return TAG_LOGINVM_CONTRA;
	}
	public String getTAG_LOGINVM_ACCE() {
		return TAG_LOGINVM_ACCE;
	}
	public String getTAG_LOGINVM_AUTENT() {
		return TAG_LOGINVM_AUTENT;
	}
	public String getTAG_MENUVM_SUBTITLE1_REQ() {
		return TAG_MENUVM_SUBTITLE1_REQ;
	}
	public String getTAG_MENUVM_SUBTITLE1_ITEM_REQ() {
		return TAG_MENUVM_SUBTITLE1_ITEM_REQ;
	}
	public String getTAG_MENUVM_SUBTITLE1_ITEM_CONCENTR() {
		return TAG_MENUVM_SUBTITLE1_ITEM_CONCENTR;
	}
	public String getTAG_MENUVM_SUBTITLE2_COTIZACIONES() {
		return TAG_MENUVM_SUBTITLE2_COTIZACIONES;
	}
	public String getTAG_MENUVM_SUBTITLE2_ITEM_COT() {
		return TAG_MENUVM_SUBTITLE2_ITEM_COT;
	}
	public String getTAG_MENUVM_SUBTITLE3_ORDENCOMPRA() {
		return TAG_MENUVM_SUBTITLE3_ORDENCOMPRA;
	}
	public String getTAG_MENUVM_SUBTITLE3_ITEM_ORDENCOMPRA() {
		return TAG_MENUVM_SUBTITLE3_ITEM_ORDENCOMPRA;
	}
	public String getTAG_MENUVM_SUBTITLE3_ITEM_CONTROL() {
		return TAG_MENUVM_SUBTITLE3_ITEM_CONTROL;
	}
	public String getTAG_MENUVM_SUBTITLE4_PANELCONTROL() {
		return TAG_MENUVM_SUBTITLE4_PANELCONTROL;
	}
	public String getTAG_MENUVM_SUBTITLE4_ITEM_CATA() {
		return TAG_MENUVM_SUBTITLE4_ITEM_CATA;
	}
	public String getTAG_MENUVM_SUBTITLE4_ITEM_PRODUC() {
		return TAG_MENUVM_SUBTITLE4_ITEM_PRODUC;
	}
	public String getTAG_MENUVM_SUBTITLE4_ITEM_PROVEEDOR() {
		return TAG_MENUVM_SUBTITLE4_ITEM_PROVEEDOR;
	}
	public String getTAG_MENUVM_SUBTITLE4_ITEM_CLIENTES() {
		return TAG_MENUVM_SUBTITLE4_ITEM_CLIENTES;
	}
	public String getTAG_MENUVM_SUBTITLE4_ITEM_USUARIO() {
		return TAG_MENUVM_SUBTITLE4_ITEM_USUARIO;
	}
	public String getTAG_MENUVM_SUBTITLE5_PERFIL() {
		return TAG_MENUVM_SUBTITLE5_PERFIL;
	}
	public String getTAG_MENUVM_SUBTITLE5_ITEM_PERFIL() {
		return TAG_MENUVM_SUBTITLE5_ITEM_PERFIL;
	}
	public String getTAG_HEADERVM_TOOLTIP_CERRAR() {
		return TAG_HEADERVM_TOOLTIP_CERRAR;
	}
	public String getTAG_HEADERVM_CODE_MESSAGE() {
		return TAG_HEADERVM_CODE_MESSAGE;
	}
	public String getTAG_HEADERVM_CODE_TITLE() {
		return TAG_HEADERVM_CODE_TITLE;
	}
	public String getGENERICZUL_TIP_GUARDAR_CAMBIOS() {
		return GENERICZUL_TIP_GUARDAR_CAMBIOS;
	}
	public String getGENERICZUL_TIP_REQUISICIONPDF() {
		return GENERICZUL_TIP_REQUISICIONPDF;
	}
	public String getGENERICZUL_TIP_BUSCADOR() {
		return GENERICZUL_TIP_BUSCADOR;
	}
	public String getGENERICZUL_TIP_CLAVE_PRODUCTO() {
		return GENERICZUL_TIP_CLAVE_PRODUCTO;
	}
	public String getGENERICZUL_COMMAND_CANCELAR() {
		return GENERICZUL_COMMAND_CANCELAR;
	}
	public String getGENERICZUL_COMMAND_ACEPTAR() {
		return GENERICZUL_COMMAND_ACEPTAR;
	}
	public String getGENERICZUL_LABEL_ACTIVO() {
		return GENERICZUL_LABEL_ACTIVO;
	}
	public String getGENERICZUL_LABEL_ACTUALIZADO() {
		return GENERICZUL_LABEL_ACTUALIZADO;
	}
	public String getGENERICZUL_LABEL_APATERNO_ABR() {
		return GENERICZUL_LABEL_APATERNO_ABR;
	}
	public String getGENERICZUL_LABEL_APATERNO() {
		return GENERICZUL_LABEL_APATERNO;
	}
	public String getGENERICZUL_LABEL_AMATERNO_ABR() {
		return GENERICZUL_LABEL_AMATERNO_ABR;
	}
	public String getGENERICZUL_LABEL_AMATERNO() {
		return GENERICZUL_LABEL_AMATERNO;
	}
	public String getGENERICZUL_LABEL_AREA_UR() {
		return GENERICZUL_LABEL_AREA_UR;
	}
	public String getGENERICZUL_LABEL_ATENCION() {
		return GENERICZUL_LABEL_ATENCION;
	}
	public String getGENERICZUL_LABEL_BANCO() {
		return GENERICZUL_LABEL_BANCO;
	}
	public String getGENERICZUL_LABEL_CALLE() {
		return GENERICZUL_LABEL_CALLE;
	}
	public String getGENERICZUL_LABEL_CIUDAD() {
		return GENERICZUL_LABEL_CIUDAD;
	}
	public String getGENERICZUL_LABEL_CLAVE() {
		return GENERICZUL_LABEL_CLAVE;
	}
	public String getGENERICZUL_LABEL_CLABE() {
		return GENERICZUL_LABEL_CLABE;
	}
	public String getGENERICZUL_LABEL_CLAVE_ARMOMIZADA() {
		return GENERICZUL_LABEL_CLAVE_ARMOMIZADA;
	}
	public String getGENERICZUL_LABEL_CONTRASENA() {
		return GENERICZUL_LABEL_CONTRASENA;
	}
	public String getGENERICZUL_LABEL_CONTRASENA_REPETIR() {
		return GENERICZUL_LABEL_CONTRASENA_REPETIR;
	}
	public String getGENERICZUL_LABEL_CUENTA_BANCARIA() {
		return GENERICZUL_LABEL_CUENTA_BANCARIA;
	}
	public String getGENERICZUL_LABEL_CURP() {
		return GENERICZUL_LABEL_CURP;
	}
	public String getGENERICZUL_LABEL_CODIGO_BARRAS_ABR() {
		return GENERICZUL_LABEL_CODIGO_BARRAS_ABR;
	}
	public String getGENERICZUL_LABEL_CODIGO_POSTAL() {
		return GENERICZUL_LABEL_CODIGO_POSTAL;
	}
	public String getGENERICZUL_LABEL_CODIGO_POSTAL_ABR() {
		return GENERICZUL_LABEL_CODIGO_POSTAL_ABR;
	}
	public String getGENERICZUL_LABEL_COLONIA() {
		return GENERICZUL_LABEL_COLONIA;
	}
	public String getGENERICZUL_LABEL_COSTO_UNITARIO() {
		return GENERICZUL_LABEL_COSTO_UNITARIO;
	}
	public String getGENERICZUL_LABEL_DESCRIPCION() {
		return GENERICZUL_LABEL_DESCRIPCION;
	}
	public String getGENERICZUL_LABEL_DIRECCION() {
		return GENERICZUL_LABEL_DIRECCION;
	}
	public String getGENERICZUL_LABEL_EMAIL() {
		return GENERICZUL_LABEL_EMAIL;
	}
	public String getGENERICZUL_LABEL_EN_EXISTENCIA() {
		return GENERICZUL_LABEL_EN_EXISTENCIA;
	}
	public String getGENERICZUL_LABEL_ESTADO() {
		return GENERICZUL_LABEL_ESTADO;
	}
	public String getGENERICZUL_LABEL_ENTIDAD() {
		return GENERICZUL_LABEL_ENTIDAD;
	}
	public String getGENERICZUL_LABEL_EXTENSION() {
		return GENERICZUL_LABEL_EXTENSION;
	}
	public String getGENERICZUL_LABEL_FAMILIA() {
		return GENERICZUL_LABEL_FAMILIA;
	}
	public String getGENERICZUL_LABEL_FAX() {
		return GENERICZUL_LABEL_FAX;
	}
	public String getGENERICZUL_LABEL_FECHA() {
		return GENERICZUL_LABEL_FECHA;
	}
	public String getGENERICZUL_LABEL_FECHA_CADUCIDAD() {
		return GENERICZUL_LABEL_FECHA_CADUCIDAD;
	}
	public String getGENERICZUL_LABEL_FOLIO() {
		return GENERICZUL_LABEL_FOLIO;
	}
	public String getGENERICZUL_LABEL_GIRO() {
		return GENERICZUL_LABEL_GIRO;
	}
	public String getGENERICZUL_LABEL_IMAGEN() {
		return GENERICZUL_LABEL_IMAGEN;
	}
	public String getGENERICZUL_LABEL_MARCA() {
		return GENERICZUL_LABEL_MARCA;
	}
	public String getGENERICZUL_LABEL_MAXIMO() {
		return GENERICZUL_LABEL_MAXIMO;
	}
	public String getGENERICZUL_LABEL_MINIMO() {
		return GENERICZUL_LABEL_MINIMO;
	}
	public String getGENERICZUL_LABEL_MODELO() {
		return GENERICZUL_LABEL_MODELO;
	}
	public String getGENERICZUL_LABEL_MONEDA() {
		return GENERICZUL_LABEL_MONEDA;
	}
	public String getGENERICZUL_LABEL_MOVIL() {
		return GENERICZUL_LABEL_MOVIL;
	}
	public String getGENERICZUL_LABEL_MUNICIPIO() {
		return GENERICZUL_LABEL_MUNICIPIO;
	}
	public String getGENERICZUL_LABEL_NATURALEZA() {
		return GENERICZUL_LABEL_NATURALEZA;
	}
	public String getGENERICZUL_LABEL_NOMBRE() {
		return GENERICZUL_LABEL_NOMBRE;
	}
	public String getGENERICZUL_LABEL_NUMERO() {
		return GENERICZUL_LABEL_NUMERO;
	}
	public String getGENERICZUL_LABEL_NUMERO_EXTERIOR() {
		return GENERICZUL_LABEL_NUMERO_EXTERIOR;
	}
	public String getGENERICZUL_LABEL_NUMERO_EXTERIOR_ABR() {
		return GENERICZUL_LABEL_NUMERO_EXTERIOR_ABR;
	}
	public String getGENERICZUL_LABEL_NUMERO_INTERIOR() {
		return GENERICZUL_LABEL_NUMERO_INTERIOR;
	}
	public String getGENERICZUL_LABEL_NUMERO_INTERIOR_ABR() {
		return GENERICZUL_LABEL_NUMERO_INTERIOR_ABR;
	}
	public String getGENERICZUL_LABEL_PAGINA_WEB() {
		return GENERICZUL_LABEL_PAGINA_WEB;
	}
	public String getGENERICZUL_LABEL_PAIS() {
		return GENERICZUL_LABEL_PAIS;
	}
	public String getGENERICZUL_LABEL_PARTIDA_GENERICA() {
		return GENERICZUL_LABEL_PARTIDA_GENERICA;
	}
	public String getGENERICZUL_LABEL_PROVEEDOR() {
		return GENERICZUL_LABEL_PROVEEDOR;
	}
	public String getGENERICZUL_LABEL_RAZON_SOCIAL() {
		return GENERICZUL_LABEL_RAZON_SOCIAL;
	}
	public String getGENERICZUL_LABEL_REPOSICION() {
		return GENERICZUL_LABEL_REPOSICION;
	}
	public String getGENERICZUL_LABEL_RFC() {
		return GENERICZUL_LABEL_RFC;
	}
	public String getGENERICZUL_LABEL_TELEFONO() {
		return GENERICZUL_LABEL_TELEFONO;
	}
	public String getGENERICZUL_LABEL_UNIDAD() {
		return GENERICZUL_LABEL_UNIDAD;
	}
	public String getGENERICZUL_LABEL_USUARIO() {
		return GENERICZUL_LABEL_USUARIO;
	}
	public String getGENERICZUL_COLUMN_ABREVIATURA() {
		return GENERICZUL_COLUMN_ABREVIATURA;
	}
	public String getGENERICZUL_COLUMN_ACTIVAR() {
		return GENERICZUL_COLUMN_ACTIVAR;
	}
	public String getGENERICZUL_COLUMN_ACTUALIZACION() {
		return GENERICZUL_COLUMN_ACTUALIZACION;
	}
	public String getGENERICZUL_COLUMN_AREA() {
		return GENERICZUL_COLUMN_AREA;
	}
	public String getGENERICZUL_COLUMN_ARTICULO() {
		return GENERICZUL_COLUMN_ARTICULO;
	}
	public String getGENERICZUL_COLUMN_CLAVE() {
		return GENERICZUL_COLUMN_CLAVE;
	}
	public String getGENERICZUL_COLUMN_CLAVE_ABR() {
		return GENERICZUL_COLUMN_CLAVE_ABR;
	}
	public String getGENERICZUL_COLUMN_CVL_PR() {
		return GENERICZUL_COLUMN_CVL_PR;
	}
	public String getGENERICZUL_COLUMN_CALLE() {
		return GENERICZUL_COLUMN_CALLE;
	}
	public String getGENERICZUL_COLUMN_CANTIDAD_ABR() {
		return GENERICZUL_COLUMN_CANTIDAD_ABR;
	}
	public String getGENERICZUL_COLUMN_CANTIDAD() {
		return GENERICZUL_COLUMN_CANTIDAD;
	}
	public String getGENERICZUL_COLUMN_CP() {
		return GENERICZUL_COLUMN_CP;
	}
	public String getGENERICZUL_COLUMN_COLONI_ABR() {
		return GENERICZUL_COLUMN_COLONI_ABR;
	}
	public String getGENERICZUL_COLUMN_COTIZACION() {
		return GENERICZUL_COLUMN_COTIZACION;
	}
	public String getGENERICZUL_COLUMN_DESCRIPCION() {
		return GENERICZUL_COLUMN_DESCRIPCION;
	}
	public String getGENERICZUL_COLUMN_ESTADO_ABR() {
		return GENERICZUL_COLUMN_ESTADO_ABR;
	}
	public String getGENERICZUL_COLUMN_EMAIL() {
		return GENERICZUL_COLUMN_EMAIL;
	}
	public String getGENERICZUL_COLUMN_EN_EXISTENCIA() {
		return GENERICZUL_COLUMN_EN_EXISTENCIA;
	}
	public String getGENERICZUL_COLUMN_FOLIO_REQ() {
		return GENERICZUL_COLUMN_FOLIO_REQ;
	}
	public String getGENERICZUL_COLUMN_FOLIO() {
		return GENERICZUL_COLUMN_FOLIO;
	}
	public String getGENERICZUL_COLUMN_FECHA() {
		return GENERICZUL_COLUMN_FECHA;
	}
	public String getGENERICZUL_COLUMN_IMPORTE() {
		return GENERICZUL_COLUMN_IMPORTE;
	}
	public String getGENERICZUL_COLUMN_MARCA() {
		return GENERICZUL_COLUMN_MARCA;
	}
	public String getGENERICZUL_COLUMN_MUNICIPIO_ABR() {
		return GENERICZUL_COLUMN_MUNICIPIO_ABR;
	}
	public String getGENERICZUL_COLUMN_MUNICIPIO() {
		return GENERICZUL_COLUMN_MUNICIPIO;
	}
	public String getGENERICZUL_COLUMN_NATURALEZA() {
		return GENERICZUL_COLUMN_NATURALEZA;
	}
	public String getGENERICZUL_COLUMN_NO() {
		return GENERICZUL_COLUMN_NO;
	}
	public String getGENERICZUL_COLUMN_NUMERO_ABR() {
		return GENERICZUL_COLUMN_NUMERO_ABR;
	}
	public String getGENERICZUL_COLUMN_NUMERO() {
		return GENERICZUL_COLUMN_NUMERO;
	}
	public String getGENERICZUL_COLUMN_NOMBRE() {
		return GENERICZUL_COLUMN_NOMBRE;
	}
	public String getGENERICZUL_COLUMN_NOMBRE_COMPLETO() {
		return GENERICZUL_COLUMN_NOMBRE_COMPLETO;
	}
	public String getGENERICZUL_COLUMN_ORDEN_COMPRA() {
		return GENERICZUL_COLUMN_ORDEN_COMPRA;
	}
	public String getGENERICZUL_COLUMN_ORGANIZACION() {
		return GENERICZUL_COLUMN_ORGANIZACION;
	}
	public String getGENERICZUL_COLUMN_PROVEEDOR() {
		return GENERICZUL_COLUMN_PROVEEDOR;
	}
	public String getGENERICZUL_COLUMN_PRECIO() {
		return GENERICZUL_COLUMN_PRECIO;
	}
	public String getGENERICZUL_COLUMN_PRECIO_UNITARIO() {
		return GENERICZUL_COLUMN_PRECIO_UNITARIO;
	}
	public String getGENERICZUL_COLUMN_PRIVILEGIOS() {
		return GENERICZUL_COLUMN_PRIVILEGIOS;
	}
	public String getGENERICZUL_COLUMN_PRODUCTO() {
		return GENERICZUL_COLUMN_PRODUCTO;
	}
	public String getGENERICZUL_COLUMN_PARTIDA_GENERICA() {
		return GENERICZUL_COLUMN_PARTIDA_GENERICA;
	}
	public String getGENERICZUL_COLUMN_REGISTRO() {
		return GENERICZUL_COLUMN_REGISTRO;
	}
	public String getGENERICZUL_COLUMN_SIMBOLO() {
		return GENERICZUL_COLUMN_SIMBOLO;
	}
	public String getGENERICZUL_COLUMN_STOCK() {
		return GENERICZUL_COLUMN_STOCK;
	}
	public String getGENERICZUL_COLUMN_TOTAL() {
		return GENERICZUL_COLUMN_TOTAL;
	}
	public String getGENERICZUL_COLUMN_UNIDAD_MEDIDA() {
		return GENERICZUL_COLUMN_UNIDAD_MEDIDA;
	}
	public String getGENERICZUL_COLUMN_UNIDAD() {
		return GENERICZUL_COLUMN_UNIDAD;
	}
	public String getGENERICZUL_COLUMN_UR() {
		return GENERICZUL_COLUMN_UR;
	}
	public String getGENERICZUL_COLUMN_USUARIO() {
		return GENERICZUL_COLUMN_USUARIO;
	}
	public String getGENERICZUL_COLUMN_VIGENCIA_INICIO() {
		return GENERICZUL_COLUMN_VIGENCIA_INICIO;
	}
	public String getGENERICZUL_COLUMN_VIGENCIA_FIN() {
		return GENERICZUL_COLUMN_VIGENCIA_FIN;
	}
	public String getREQUISICIONZUL_TITLE() {
		return REQUISICIONZUL_TITLE;
	}
	public String getREQUISICIONZUL_TIP_REQUISICION_NUEVA() {
		return REQUISICIONZUL_TIP_REQUISICION_NUEVA;
	}
	public String getREQUISICIONZUL_TIP_REQUISICION_CANCELADA() {
		return REQUISICIONZUL_TIP_REQUISICION_CANCELADA;
	}
	public String getREQUISICIONZUL_TIP_REQUISICION_ACEPTADA() {
		return REQUISICIONZUL_TIP_REQUISICION_ACEPTADA;
	}
	public String getREQUISICIONZUL_TIP_BUSCA_REQUISICION() {
		return REQUISICIONZUL_TIP_BUSCA_REQUISICION;
	}
	public String getREQUISICIONZUL_TITLE_LISTAPRODUCTOS() {
		return REQUISICIONZUL_TITLE_LISTAPRODUCTOS;
	}
	public String getREQUISICIONZUL_TITLE_BANDEJA_REQUISICION() {
		return REQUISICIONZUL_TITLE_BANDEJA_REQUISICION;
	}
	public String getREQUISICIONZUL_LABEL_AREASOLICITANTE() {
		return REQUISICIONZUL_LABEL_AREASOLICITANTE;
	}
	public String getREQUISICIONZUL_LABEL_PROGRAMA() {
		return REQUISICIONZUL_LABEL_PROGRAMA;
	}
	public String getREQUISICIONZUL_LABEL_PROYECTO() {
		return REQUISICIONZUL_LABEL_PROYECTO;
	}
	public String getREQUISICIONZUL_LABEL_FUENTE_FINANCIAMIENTO() {
		return REQUISICIONZUL_LABEL_FUENTE_FINANCIAMIENTO;
	}
	public String getREQUISICIONZUL_LABEL_PUESTO() {
		return REQUISICIONZUL_LABEL_PUESTO;
	}
	public String getREQUISICIONZUL_LABEL_JUSTIFICACION() {
		return REQUISICIONZUL_LABEL_JUSTIFICACION;
	}
	public String getREQUISICIONZUL_LABEL_NUMERO_INVENTARIO() {
		return REQUISICIONZUL_LABEL_NUMERO_INVENTARIO;
	}
	public String getREQUISICIONZUL_LABEL_PRODUCTOS_COUNT() {
		return REQUISICIONZUL_LABEL_PRODUCTOS_COUNT;
	}
	public String getREQUISICIONZUL_LABEL_CONTRATO() {
		return REQUISICIONZUL_LABEL_CONTRATO;
	}
	public String getREQUISICIONZUL_LABEL_ALMACEN() {
		return REQUISICIONZUL_LABEL_ALMACEN;
	}
	public String getREQUISICIONZUL_LABEL_CONSUMO() {
		return REQUISICIONZUL_LABEL_CONSUMO;
	}
	public String getREQUISICIONZUL_TIP_COMMAND_REQUISICIONNUEVA() {
		return REQUISICIONZUL_TIP_COMMAND_REQUISICIONNUEVA;
	}
	public String getREQUISICIONZUL_TIP_BUSCAR_AREA() {
		return REQUISICIONZUL_TIP_BUSCAR_AREA;
	}
	public String getREQUISICIONZUL_TIP_BUSCAR_PROGRAMA() {
		return REQUISICIONZUL_TIP_BUSCAR_PROGRAMA;
	}
	public String getREQUISICIONZUL_TIP_BUSCAR_PROYECTO() {
		return REQUISICIONZUL_TIP_BUSCAR_PROYECTO;
	}
	public String getREQUISICIONZUL_TIP_BUSCAR_FUENTE_FINANCIAMIENTO() {
		return REQUISICIONZUL_TIP_BUSCAR_FUENTE_FINANCIAMIENTO;
	}
	public String getREQUISICIONZUL_TIP_BUSCAR_JUSTIFICACION() {
		return REQUISICIONZUL_TIP_BUSCAR_JUSTIFICACION;
	}
	public String getREQUISICIONZUL_TIP_BUSCAR_PRODUCTOS() {
		return REQUISICIONZUL_TIP_BUSCAR_PRODUCTOS;
	}
	public String getREQUISICIONZUL_TIP_BUSCAR_PARTIDA_GENERICA() {
		return REQUISICIONZUL_TIP_BUSCAR_PARTIDA_GENERICA;
	}
	public String getREQUISICIONZUL_TIP_PRODUCTOS_ENTREGADOS() {
		return REQUISICIONZUL_TIP_PRODUCTOS_ENTREGADOS;
	}
	public String getREQUISICIONZUL_TIP_ADD_PRODUCTO() {
		return REQUISICIONZUL_TIP_ADD_PRODUCTO;
	}
	public String getREQUISICIONZUL_TIP_REMOVE_PRODUCTO() {
		return REQUISICIONZUL_TIP_REMOVE_PRODUCTO;
	}
	public String getWINDOW_SELECT_UR_TITLE() {
		return WINDOW_SELECT_UR_TITLE;
	}
	public String getWINDOW_SELECT_UR_EMPTY() {
		return WINDOW_SELECT_UR_EMPTY;
	}
	public String getWINDOW_SELECT_PROYECTO_TITLE() {
		return WINDOW_SELECT_PROYECTO_TITLE;
	}
	public String getWINDOW_SELECT_PROYECTO_EMPTY() {
		return WINDOW_SELECT_PROYECTO_EMPTY;
	}
	public String getWINDOW_SELECT_PROGRAMA_TITLE() {
		return WINDOW_SELECT_PROGRAMA_TITLE;
	}
	public String getWINDOW_SELECT_PROGRAMA_EMPTY() {
		return WINDOW_SELECT_PROGRAMA_EMPTY;
	}
	public String getWINDOW_SELECT_PARTIDA_GENERICA_TITLE() {
		return WINDOW_SELECT_PARTIDA_GENERICA_TITLE;
	}
	public String getWINDOW_SELECT_PARTIDA_GENERICA_EMPTY() {
		return WINDOW_SELECT_PARTIDA_GENERICA_EMPTY;
	}
	public String getWINDOW_SELECT_JUSTIFICACION_TITLE() {
		return WINDOW_SELECT_JUSTIFICACION_TITLE;
	}
	public String getWINDOW_SELECT_JUSTIFICACION_EMPTY() {
		return WINDOW_SELECT_JUSTIFICACION_EMPTY;
	}
	public String getWINDOW_SELECT_FUENTE_FINANCIAMIENTO_TITLE() {
		return WINDOW_SELECT_FUENTE_FINANCIAMIENTO_TITLE;
	}
	public String getWINDOW_SELECT_FUENTE_FINANCIAMIENTO_EMPTY() {
		return WINDOW_SELECT_FUENTE_FINANCIAMIENTO_EMPTY;
	}
	public String getWINDOW_BUSCADOR_PRODUCTOS_TITLE() {
		return WINDOW_BUSCADOR_PRODUCTOS_TITLE;
	}
	public String getWINDOW_BUSCADOR_PRODUCTOS_EMPTY() {
		return WINDOW_BUSCADOR_PRODUCTOS_EMPTY;
	}
	public String getWINDOW_MESSAGE1_TITLE() {
		return WINDOW_MESSAGE1_TITLE;
	}
	public String getWINDOW_MESSAGE1_CONTENT() {
		return WINDOW_MESSAGE1_CONTENT;
	}
	public String getWINDOW_MESSAGE2_CONTENT() {
		return WINDOW_MESSAGE2_CONTENT;
	}
	public String getREQUISICIONZUL_BUSQUEDA_VACIA() {
		return REQUISICIONZUL_BUSQUEDA_VACIA;
	}
	public String getREQUISICIONZUL_BANDEJA_VACIA() {
		return REQUISICIONZUL_BANDEJA_VACIA;
	}
	public String getGENERICZUL_LABEL_BUSCADOR() {
		return GENERICZUL_LABEL_BUSCADOR;
	}
	public String getGENERICZUL_TIP_FOLIO_REQUISICION() {
		return GENERICZUL_TIP_FOLIO_REQUISICION;
	}
	public String getGENERICZUL_TIP_CLAVE_AREA() {
		return GENERICZUL_TIP_CLAVE_AREA;
	}
	public String getGENERICZUL_TIP_CANTIDAD_PRODUCTO() {
		return GENERICZUL_TIP_CANTIDAD_PRODUCTO;
	}
	public String getCONCENTRADOZUL_TIP_GENERAR_COTIZACION() {
		return CONCENTRADOZUL_TIP_GENERAR_COTIZACION;
	}
	public String getCONCENTRADOZUL_TITLE_MAIN_PANEL() {
		return CONCENTRADOZUL_TITLE_MAIN_PANEL;
	}
	public String getTAG_LOGINVM_PROVEEDORES() {
		return TAG_LOGINVM_PROVEEDORES;
	}
	public String getGENERICMESSAGE_NO_EXISTE_USUARIO() {
		return GENERICMESSAGE_NO_EXISTE_USUARIO;
	}
	public String getGENERICMESSAGE_INGRESAR_VALOR_REGISTRO() {
		return GENERICMESSAGE_INGRESAR_VALOR_REGISTRO;
	}
	public String getGENERICMESSAGE_SERVICIO_NO_ACTIVADO() {
		return GENERICMESSAGE_SERVICIO_NO_ACTIVADO;
	}
	public String getGENERICMESSAGE_CREDENCIALES_INCORRECTAS() {
		return GENERICMESSAGE_CREDENCIALES_INCORRECTAS;
	}
	public String getREQUISICIONZUL_TIP_SALVAR_CAMBIOS() {
		return REQUISICIONZUL_TIP_SALVAR_CAMBIOS;
	}
	public String getREQUISICIONZUL_TIP_REQUISICION_PENDIENTE() {
		return REQUISICIONZUL_TIP_REQUISICION_PENDIENTE;
	}
	public String getREQUISICIONZUL_LIST1() {
		return REQUISICIONZUL_LIST1;
	}
	public String getTAG_MENUVM_SUBTITLE3_ITEM_KARDEX() {
		return TAG_MENUVM_SUBTITLE3_ITEM_KARDEX;
	}
	
}
